// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: api/swagger.proto

package gen_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Swagger_GetLost_FullMethodName = "/swagger.Swagger/GetLost"
	Swagger_GetOk_FullMethodName   = "/swagger.Swagger/GetOk"
)

// SwaggerClient is the client API for Swagger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwaggerClient interface {
	GetLost(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MyEnum, error)
	GetOk(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MyEnum, error)
}

type swaggerClient struct {
	cc grpc.ClientConnInterface
}

func NewSwaggerClient(cc grpc.ClientConnInterface) SwaggerClient {
	return &swaggerClient{cc}
}

func (c *swaggerClient) GetLost(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MyEnum, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyEnum)
	err := c.cc.Invoke(ctx, Swagger_GetLost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swaggerClient) GetOk(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MyEnum, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyEnum)
	err := c.cc.Invoke(ctx, Swagger_GetOk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwaggerServer is the server API for Swagger service.
// All implementations must embed UnimplementedSwaggerServer
// for forward compatibility
type SwaggerServer interface {
	GetLost(context.Context, *emptypb.Empty) (*MyEnum, error)
	GetOk(context.Context, *emptypb.Empty) (*MyEnum, error)
	mustEmbedUnimplementedSwaggerServer()
}

// UnimplementedSwaggerServer must be embedded to have forward compatible implementations.
type UnimplementedSwaggerServer struct {
}

func (UnimplementedSwaggerServer) GetLost(context.Context, *emptypb.Empty) (*MyEnum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLost not implemented")
}
func (UnimplementedSwaggerServer) GetOk(context.Context, *emptypb.Empty) (*MyEnum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOk not implemented")
}
func (UnimplementedSwaggerServer) mustEmbedUnimplementedSwaggerServer() {}

// UnsafeSwaggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwaggerServer will
// result in compilation errors.
type UnsafeSwaggerServer interface {
	mustEmbedUnimplementedSwaggerServer()
}

func RegisterSwaggerServer(s grpc.ServiceRegistrar, srv SwaggerServer) {
	s.RegisterService(&Swagger_ServiceDesc, srv)
}

func _Swagger_GetLost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerServer).GetLost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Swagger_GetLost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerServer).GetLost(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swagger_GetOk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerServer).GetOk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Swagger_GetOk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerServer).GetOk(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Swagger_ServiceDesc is the grpc.ServiceDesc for Swagger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Swagger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swagger.Swagger",
	HandlerType: (*SwaggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLost",
			Handler:    _Swagger_GetLost_Handler,
		},
		{
			MethodName: "GetOk",
			Handler:    _Swagger_GetOk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/swagger.proto",
}
