// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/swagger.proto

package gen_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyEnum_Value int32

const (
	MyEnum_LOST MyEnum_Value = 0
	MyEnum_OK   MyEnum_Value = 1
)

// Enum value maps for MyEnum_Value.
var (
	MyEnum_Value_name = map[int32]string{
		0: "LOST",
		1: "OK",
	}
	MyEnum_Value_value = map[string]int32{
		"LOST": 0,
		"OK":   1,
	}
)

func (x MyEnum_Value) Enum() *MyEnum_Value {
	p := new(MyEnum_Value)
	*p = x
	return p
}

func (x MyEnum_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyEnum_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_api_swagger_proto_enumTypes[0].Descriptor()
}

func (MyEnum_Value) Type() protoreflect.EnumType {
	return &file_api_swagger_proto_enumTypes[0]
}

func (x MyEnum_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyEnum_Value.Descriptor instead.
func (MyEnum_Value) EnumDescriptor() ([]byte, []int) {
	return file_api_swagger_proto_rawDescGZIP(), []int{0, 0}
}

type MyEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value MyEnum_Value `protobuf:"varint,1,opt,name=value,proto3,enum=swagger.MyEnum_Value" json:"value,omitempty"`
}

func (x *MyEnum) Reset() {
	*x = MyEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_swagger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyEnum) ProtoMessage() {}

func (x *MyEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_swagger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyEnum.ProtoReflect.Descriptor instead.
func (*MyEnum) Descriptor() ([]byte, []int) {
	return file_api_swagger_proto_rawDescGZIP(), []int{0}
}

func (x *MyEnum) GetValue() MyEnum_Value {
	if x != nil {
		return x.Value
	}
	return MyEnum_LOST
}

var File_api_swagger_proto protoreflect.FileDescriptor

var file_api_swagger_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x06, 0x4d,
	0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d,
	0x79, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x19, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x4f, 0x53, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x32, 0x73, 0x0a,
	0x07, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x73, 0x77,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x32,
	0x0a, 0x05, 0x47, 0x65, 0x74, 0x4f, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0f, 0x2e, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d,
	0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_swagger_proto_rawDescOnce sync.Once
	file_api_swagger_proto_rawDescData = file_api_swagger_proto_rawDesc
)

func file_api_swagger_proto_rawDescGZIP() []byte {
	file_api_swagger_proto_rawDescOnce.Do(func() {
		file_api_swagger_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_swagger_proto_rawDescData)
	})
	return file_api_swagger_proto_rawDescData
}

var file_api_swagger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_swagger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_swagger_proto_goTypes = []any{
	(MyEnum_Value)(0),     // 0: swagger.MyEnum.Value
	(*MyEnum)(nil),        // 1: swagger.MyEnum
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_api_swagger_proto_depIdxs = []int32{
	0, // 0: swagger.MyEnum.value:type_name -> swagger.MyEnum.Value
	2, // 1: swagger.Swagger.GetLost:input_type -> google.protobuf.Empty
	2, // 2: swagger.Swagger.GetOk:input_type -> google.protobuf.Empty
	1, // 3: swagger.Swagger.GetLost:output_type -> swagger.MyEnum
	1, // 4: swagger.Swagger.GetOk:output_type -> swagger.MyEnum
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_swagger_proto_init() }
func file_api_swagger_proto_init() {
	if File_api_swagger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_swagger_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MyEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_swagger_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_swagger_proto_goTypes,
		DependencyIndexes: file_api_swagger_proto_depIdxs,
		EnumInfos:         file_api_swagger_proto_enumTypes,
		MessageInfos:      file_api_swagger_proto_msgTypes,
	}.Build()
	File_api_swagger_proto = out.File
	file_api_swagger_proto_rawDesc = nil
	file_api_swagger_proto_goTypes = nil
	file_api_swagger_proto_depIdxs = nil
}
